#pragma once

#pragma once
void TestCString();
void CstringPring();
void Assignment4a();
void Assignment4b();
void TestStrTok();
void TestTypecoversion();
void TestStringType();
void getDogInfo();
void TestStringType2();
void TestColorEnum();
void ExamineBasicRandomNumbers();
void GuessingCame();
void ExploreBitwiseBasics();
void PrintNumberOfWheels();
void StartGameLoop();
void TestPairTemplate();
void TestSTLObjectVector();
void ErrorHandlingExample1();
void ErrorHandlingExample2();
